### PR TITLE
Add ja Translation

### PR DESCRIPTION
**Pull request by shg166**
Hi, I have added a Japanese translation.
If you have any plans to update, please do so with me.
It would be very helpful if you could rework the old mod and make it compatible with the current version.

### CODE REVIEW

**Comment by TheDogKSP** [comment]
Thank you!
This mod is not based on any older mod, but should include most features of Tree Fire Control.

Which features from an older mod are you missing? Maybe they can be added here.

**Comment by shg166** [comment]
Would it be possible to add the ability to disable fire outbreaks in the Campus areas and Airport areas?
The No Park Building Fires MOD only applies to Park areas.

If it can be implemented, it would be useful for those who don't have the Disaster DLC.

**Comment by TheDogKSP** [comment]
that should be possible, I'll look into it!

**Comment by TheDogKSP** [comment]
@shg166 Good suggestion, it is implemented now in the latest version!

**Comment by shg166** [comment]
Excellent!
Thank you, I will update the mod and check it out.
I will pull request the translation of the added parts later.

**Pull request merged**
